### ISSUE TITLE
Function calls are not correctly highlighted.

### ISSUE THREAD

**Issue by mapringg** [tonsky/sublime-scheme-alabaster#14]
<img width="877" alt="Screen Shot 2021-04-13 at 00 13 31" src="https://user-images.githubusercontent.com/15067237/114434585-62148b00-9bed-11eb-8ce2-75de6baf1b86.png">
<img width="919" alt="Screen Shot 2021-04-13 at 00 15 01" src="https://user-images.githubusercontent.com/15067237/114434612-68a30280-9bed-11eb-879f-998d0b64094d.png">
<img width="1288" alt="Screen Shot 2021-04-13 at 00 15 09" src="https://user-images.githubusercontent.com/15067237/114434619-69d42f80-9bed-11eb-8b43-4da5c3619969.png">

I am not getting the correct syntax highlighting. My sublime version is build 4102 and from the first screenshot, I do not think that it is a problem with detecting the correct syntax because the default color scheme seems to handle it correctly.

**Comment by tonsky** [comment]
This is supposed to be minimal color scheme that minimizes noise. I’d say it works as intended
