### ISSUE TITLE
Issue with wallaby.js

### ISSUE THREAD

**Issue by lamartire** [tonsky/sublime-scheme-alabaster#2]
![image](https://user-images.githubusercontent.com/13414205/50560597-89dccf00-0d13-11e9-8d10-a0e411b5c6d8.png)

Hello! There is an issue with wallaby.js sidebar markers. First case markers must be green, all markers below must be red.

**Comment by tonsky** [comment]
This seems to be an issue with any light scheme. Please report it to Wallaby

**Comment by lamartire** [comment]
@tonsky in [this comment](https://github.com/wallabyjs/public/issues/1952#issuecomment-451063304) author of wallaby said as that issue on the theme side. Any ideas?

**Comment by tonsky** [comment]
I’ll let him figure it out. I’m sure light themes are doing absolutely nothing to mess up with Wallaby specifically
