### ISSUE TITLE
highlighting map keys

### ISSUE THREAD

**Issue by p00f** [tonsky/sublime-scheme-alabaster#20]
Hey! I'm trying to port this theme to neovim.

In sublime text, clojure map keys are highlighted magenta and lua table keys are highlighted green, what is the correct colour?

**Comment by p00f** [comment]
I guessed the clojure's magenta would be correct since that is what is shown in the screenshots but I wanted to ask anyway

**Comment by p00f** [comment]
(similarly, should json keys also be magenta? how does one decide?)

**Comment by tonsky** [comment]
The distinction is by data type. All strings are green, and all other types of constants (numbers, keywords, booleans) magenta. Clojure map keys are  usually keywords, but not always

**Comment by p00f** [comment]
Thanks
