### ISSUE TITLE
For another editor?

### ISSUE THREAD

**Issue by Alexey-T** [tonsky/sublime-scheme-alabaster#5]
Hi, good light color scheme.
Is it possible to paint it for CudaText too, please?
http://wiki.freepascal.org/CudaText#Color_themes

**Comment by tonsky** [comment]
Sure, go ahead! If you want, I could add a link to your implementation to the Readme once it’s done

**Comment by Alexey-T** [comment]
I made it. it is in CudaText AddonManager plugin. it used 5 base colors + old ones for background block 
hilites. Examples

![screenshot from 2019-03-01 19-21-04](https://user-images.githubusercontent.com/4154978/53651205-2a3d6a00-3c57-11e9-9613-7e4b9e40b994.png)

![screenshot from 2019-03-01 19-21-26](https://user-images.githubusercontent.com/4154978/53651225-37f2ef80-3c57-11e9-8375-e1ef2287ba34.png)

**Comment by Alexey-T** [comment]
I dont know how to use "blue - global definitions" for e.g. CSS/C++/HTML/JS. How to do it?

**Comment by Alexey-T** [comment]
Fixed- used "blue" too; removed bold styles.

![screenshot from 2019-03-01 19-32-40](https://user-images.githubusercontent.com/4154978/53651969-daf83900-3c58-11e9-8abe-4d7f322a8053.png)

**Comment by Alexey-T** [comment]
Alabaster BG
![screenshot from 2019-03-01 19-58-24](https://user-images.githubusercontent.com/4154978/53653553-95d60600-3c5c-11e9-9bc8-d8db1e67de56.png)

**Comment by tonsky** [comment]
Do you have a link to that theme specifically?

**Comment by Alexey-T** [comment]
It is on https://sourceforge.net/projects/cudatext/files/addons/themes/theme.Alabaster.zip/download
