### ISSUE TITLE
Alabaster BG highlighting inconsistent between languages

### ISSUE THREAD

**Issue by Nelarius** [tonsky/sublime-scheme-alabaster#6]
I like the idea of the Alabaster BG theme a lot! 🙂  I tried it out in a few different projects of mine and noticed that the background highlighting doesn't seem to work the same way for different languages.

For instance, in C++ and Rust, the comment background is the full width of the column, and literals like numbers and booleans don't have a background.

<img width="723" alt="Screen Shot 2019-04-02 at 8 44 58" src="https://user-images.githubusercontent.com/3276684/55379096-58e38480-5524-11e9-9f2d-605a122c603b.png">

**Comment by tonsky** [comment]
That depends on how language grammar is implemented. Most should use more or less the same scopes, but sometimes there are mistakes/exceptions/nuances. Not much I can do from the color scheme side, unfortunately
