### ISSUE TITLE
Just want to share my appreciation

### ISSUE THREAD

**Issue by KevinSjoberg** [tonsky/sublime-scheme-alabaster#8]
Hi @tonsky! 👋 

I've been using Alabaster for quite some time now and it's been an absolute blast. I really think it makes a huge difference in how I read and think about my code. Keep up the good work, it's really an amazing color scheme. ❤️

If you ever set up a way of supporting your work, I'd be happy to!

**Comment by tonsky** [comment]
Thanks Kevin! If you like, my patreon page is here https://www.patreon.com/tonsky
