### ISSUE TITLE
Inconsistent highlighting in Haskell

### ISSUE THREAD

**Issue by KevinSjoberg** [tonsky/sublime-scheme-alabaster#9]
Just noticed that the syntax highlighting seem to be inconsistent with Haskell. I'm using [Sublime Haskell](https://github.com/SublimeHaskell/SublimeHaskell) for improved syntax highlighting and this is what I'm seeing.

<img width="608" alt="Screenshot 2019-12-08 at 08 46 11" src="https://user-images.githubusercontent.com/503025/70386205-35b48300-1997-11ea-89f9-414d35a19e2c.png">

I would expect that either all applications of `print` are highlighted together with the application of `createEmail` or that none are. Right now it seems like only the very first operation is highlighted.

Is this expected or a bug?

**Comment by KevinSjoberg** [comment]
Turns out it's the same with any color scheme. My bad.

**Comment by tonsky** [comment]
Unlike other color schemes that normally highlight all function invocations, Alabaster tries to only highlight function _definitions_. For this to work, though, language grammar should parse it correcly. In this case first print is recognized as a function definition for some reason? Please report it to the language grammar repository, it’s their issue
